#Ci de nivel 01- Disparo Manual a partir de um clique

#nome das op de pipe
name: 'Execução Manual'

# trigger ou gatilhos de execução
# gatilho de exec manual = workflow_dispatch

on:
    workflow_dispatch:


jobs:
    #descrição do job 
    e2e-testes:
        #maquina que o job vai executar
        runs-on: ['ubuntu-latest']
        # passo a passo das ações do job
        steps: 
            - uses: actions/checkout@v4
            - name: instalando Yarn
              run: npm install -g yarn

            - name: instalando dependências Yarn 
              run: yarn
            
            - name: instalando Playwright
              run: yarn playwright install

            - name: Testes E2E
              run: yarn run e2e
            #- uses: actions/setup-node@v4
             # with:
              #          node-version: lts/*  